'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property customer_id As String
    Public Property company_name As String
    Public Property contact_name As String
    Public Property contact_title As String
    Public Property address As String
    Public Property postal_code As Nullable(Of Long)
    Public Property city As String
    Public Property state As String
    Public Property country As String
    Public Property phone_number As Nullable(Of Long)

End Class
